# mammoth_os/agents/curriculum_agent.py

import os
from typing import Dict, Any

from .base_agent import BaseAgent


class CurriculumAgent(BaseAgent):
    """
    CurriculumAgent (Rugged MammothOS survival aesthetic)
    - Writes lesson/module files
    - Generates curriculum content
    - Creates directories (approval-gated)
    - Overwrites files (approval-gated)
    """

    name = "CurriculumAgent"

    def __init__(self, router):
        super().__init__(router)


    def execute_action(self, action_type: str, target: str, details: Dict[str, Any]):
        if action_type == "write_file":
            return self._write_file(target, details)

        if action_type == "generate_content":
            return self._generate_content(target, details)

        if action_type == "create_directory":
            return self._create_directory(target)

        if action_type == "overwrite_file":
            return self._overwrite_file(target, details)

        return {
            "status": "unknown_action",
            "agent": self.name,
            "action": action_type,
            "target": target,
        }

    # --- Core curriculum operations ----------------------------------------

    def _write_file(self, target: str, details: Dict[str, Any]):
        """
        Write a new curriculum file.
        details:
            - content: str (required)
        """
        content = details.get("content")
        if content is None:
            return {"status": "error", "reason": "Missing 'content' in details"}

        os.makedirs(os.path.dirname(target), exist_ok=True)

        with open(target, "w", encoding="utf-8") as f:
            f.write(content)

        return {
            "status": "ok",
            "agent": self.name,
            "action": "write_file",
            "target": target,
        }

    def _generate_content(self, target: str, details: Dict[str, Any]):
        """
        Generate curriculum content.
        For now: simple placeholder.
        Later: call DeepSeek or your Curriculum Engine.
        """
        topic = details.get("topic", "Untitled Module")
        generated = f"# {topic}\n\nGenerated by CurriculumAgent.\n"

        os.makedirs(os.path.dirname(target), exist_ok=True)

        with open(target, "w", encoding="utf-8") as f:
            f.write(generated)

        return {
            "status": "ok",
            "agent": self.name,
            "action": "generate_content",
            "target": target,
            "generated": generated,
        }

    def _create_directory(self, target: str):
        """
        Create a new curriculum directory.
        Approval-gated by Cortex.
        """
        if os.path.exists(target):
            return {"status": "exists", "target": target}

        os.makedirs(target, exist_ok=True)

        return {
            "status": "ok",
            "agent": self.name,
            "action": "create_directory",
            "target": target,
        }

    def _overwrite_file(self, target: str, details: Dict[str, Any]):
        """
        Overwrite an existing curriculum file.
        Approval-gated by Cortex.
        """
        content = details.get("content")
        if content is None:
            return {"status": "error", "reason": "Missing 'content' in details"}

        if not os.path.exists(target):
            return {"status": "error", "reason": f"File not found: {target}"}

        with open(target, "w", encoding="utf-8") as f:
            f.write(content)

        return {
            "status": "ok",
            "agent": self.name,
            "action": "overwrite_file",
            "target": target,
        }
