# mammoth_os/agents/plant_the_seed_agent.py
"""
PlantTheSeedAgent — Elite Idea Validation Engine

Takes raw business ideas and delivers a structured validation framework:
testable hypothesis, market signals, 3 executable first actions, a 7-day
sprint plan, risks with mitigations, and a clear go/no-go verdict.

Zero templates. Every response generated by LLM against the actual prompt.
"""

from __future__ import annotations

import asyncio
import concurrent.futures
import json
import logging
from datetime import datetime, timezone
from typing import Any, Dict, Union

from mammoth_os.llm_completion import complete
from mammoth_os.research_quality import strip_reasoning

from .base_agent import BaseAgent

logger = logging.getLogger("mammoth.agents.plant_seed")

SYSTEM_PROMPT = """You assess the user's specific idea and propose practical ways to validate it.
Do not assume an operator, business, industry, or location unless the user provides it.
For design/software ideas, evaluate usability, accessibility, implementation tradeoffs,
and reversible validation steps rather than inventing local market demand.

Your job: take a raw seed idea and answer ONE question with precision:
"Is this worth pursuing — and exactly what do you do in the next 7 days to find out?"

Think like a YC partner crossed with a seasoned small business operator.
Be ruthlessly specific. No generic advice. Every action must be executable with <$100 and no team.

Respond in this exact JSON structure:
{
  "idea_summary": "One crisp sentence restating the core idea — sharpen it if the original is fuzzy",
  "hypothesis": "Testable statement: IF [the user does X] THEN [we expect Y outcome] BECAUSE [underlying assumption Z]",
  "market_signal": "Relevant evidence or signals; distinguish assumptions from verified facts and state when market analysis is not applicable",
  "addressable_demand": "Who specifically wants this, how many of them exist in the target area, and how do you know",
  "validation_steps": [
    {
      "step": 1,
      "action": "Specific action to validate the core hypothesis",
      "method": "Exact method suited to this idea, such as a usability check, prototype comparison, or customer interviews",
      "cost": "$ estimate",
      "timeline": "Day 1-2 / This week / etc.",
      "success_indicator": "Specific observable YES — e.g. '2 of 3 people ask where to buy it'"
    },
    {
      "step": 2,
      "action": "...",
      "method": "...",
      "cost": "...",
      "timeline": "...",
      "success_indicator": "..."
    },
    {
      "step": 3,
      "action": "...",
      "method": "...",
      "cost": "...",
      "timeline": "...",
      "success_indicator": "..."
    }
  ],
  "first_3_actions": [
    "Action 1 — executable TODAY, zero cost, under 2 hours",
    "Action 2 — executable this week, under $25",
    "Action 3 — executable this week, validates real demand (not just interest)"
  ],
  "risks": [
    {
      "risk": "Specific risk that could kill this idea",
      "severity": "Low / Medium / High",
      "mitigation": "Concrete step to reduce this risk before committing resources"
    },
    {
      "risk": "...",
      "severity": "...",
      "mitigation": "..."
    }
  ],
  "seven_day_sprint": "What a focused, realistic 7-day validation sprint looks like — day by day or phase by phase",
  "kill_criteria": "The specific observable signal that tells you to stop and move on — be ruthless",
  "moat": "What would make this hard to copy once it works — even a small one",
  "verdict": "Plant it 🌱 / Prototype first 🔨 / Needs more research 🔍 / Kill it ❌",
  "verdict_rationale": "2-3 sentences — why this verdict, what's the biggest risk, what's the biggest opportunity"
}

CRITICAL: The validation_steps array MUST contain between 3 and 5 items. Never leave it empty.
The hypothesis field MUST be specific to the idea described in this prompt — never reference any other business ideas or prior context.
Return ONLY the JSON. No preamble. No explanation outside the JSON.
"""


class PlantTheSeedAgent(BaseAgent):
    """Elite idea validation and business seed analysis agent."""

    name = "PlantTheSeedAgent"

    def run(self, prompt: Union[str, Dict[str, Any]]) -> Dict[str, Any]:
        if isinstance(prompt, dict) and "topic" in prompt and not any(
            prompt.get(key) for key in ("prompt", "idea", "task", "content")
        ):
            return self._run_learning_seed(prompt)
        prompt_text, context = self._parse_input(prompt)
        if not prompt_text:
            return self._error_response("No seed idea provided — describe the idea you want to validate.")
        try:
            return self._run_async(self._validate_idea(prompt_text, context))
        except Exception as exc:
            logger.error(f"PlantTheSeedAgent run failed: {exc}")
            return self._error_response("Idea assessment failed. Check runtime availability and try again.")

    @staticmethod
    def _run_learning_seed(payload: Dict[str, Any]) -> Dict[str, Any]:
        topic = str(payload.get("topic") or "").strip()
        lesson_title = str(payload.get("lesson_title") or "").strip()
        module_title = str(payload.get("module_title") or "").strip()
        anchor = lesson_title or module_title or topic
        placeholder_values = {"", "unknown", "placeholder", "tbd", "n/a", "none"}
        if topic.lower() in placeholder_values or (lesson_title and lesson_title.lower() in placeholder_values):
            return {
                "status": "needs_context",
                "agent": "PlantTheSeedAgent",
                "mode": "learning_seed",
                "summary": "PlantTheSeed needs a real lesson or learning topic before it can make a useful recommendation.",
                "approval_gate": {"requires_review": False, "reason": "context required"},
                "quality_flags": ["needs_context", "placeholder_target_rejected"],
            }

        try:
            progress = float(payload.get("progress_score", 0.5))
        except (TypeError, ValueError):
            progress = 0.5
        progress = max(0.0, min(1.0, progress))
        next_focus = str(payload.get("next_focus") or "one focused practice step").strip()
        recommendations = [
            f"Anchor the next step to {anchor}.",
            "Keep the scope small enough to verify immediately.",
            f"Turn {next_focus} into one concrete practice step.",
        ]
        if progress < 0.5:
            recommendations.append("Use one example, one explanation, and one check for understanding.")
        tags = ["atlas"] if "atlas" in topic.lower() else []
        if progress < 0.5:
            tags.append("needs_foundation")
        summary = (
            f"{anchor} needs a smaller, repeatable rep before the learner moves on."
            if progress < 0.5
            else f"{anchor} is stable enough to keep compounding with one small daily rep."
        )
        return {
            "status": "ok",
            "agent": "PlantTheSeedAgent",
            "mode": "learning_seed",
            "topic": topic,
            "seed": f"Plant the seed for {anchor} with one small, concrete learning rep.",
            "expansion": f"Build a repeatable practice loop around {anchor}, then verify it with a short example.",
            "action": f"Practice {next_focus} with one example tied to {anchor}.",
            "summary": summary,
            "tags": tags,
            "follow_up": f"What changed after the next practice rep for {anchor}?",
            "recommendations": recommendations[:4],
            "approval_gate": {"requires_review": False, "reason": "learning guidance only"},
            "quality_flags": ["learning_context_grounded", "progress_aware"],
        }

    def execute_action(
        self, action_type: str, target: str, details: Dict[str, Any]
    ) -> Dict[str, Any]:
        payload = dict(details or {})
        if "prompt" not in payload:
            payload["prompt"] = str(target or "").strip()
        return {**self.run(payload), "action": action_type, "target": target}

    async def _validate_idea(
        self, prompt_text: str, context: Dict[str, Any]
    ) -> Dict[str, Any]:
        from mammoth_os.llm_client import get_llm_client
        client = get_llm_client()
        user_message = (
            f"Seed idea to validate: {prompt_text}\n\n"
            "IMPORTANT: Your entire response must be about THIS specific idea only. "
            "Do not reference any other business ideas or prior context."
        )
        if context:
            user_message += f"\n\nUser-provided context:\n{json.dumps(context, default=str)}"
        diagnostics = []
        parsed = {}
        issues = []
        repair = ""
        for attempt in range(2):
            result = await complete(
                client, user_message + repair, system_prompt=SYSTEM_PROMPT,
                max_tokens=3500, temperature=0.4, decision_json=True,
            )
            diagnostics.append({
                "finish_reason": result.finish_reason, "usage": result.usage,
                "model": result.model or getattr(client, "model", ""),
            })
            cleaned, _ = strip_reasoning(result.text)
            parsed = self._extract_json(cleaned)
            issues = self._validation_errors(parsed)
            if result.finish_reason == "length":
                issues = ["output_limit"]
            elif result.finish_reason in {"refusal", "content_filter"}:
                issues = ["provider_refusal"]
            elif result.text.startswith("[LOCAL_ADAPTER]"):
                issues = ["offline"]
            if not issues:
                break
            logger.warning("Idea assessment rejected (attempt %s): %s", attempt + 1, ", ".join(issues))
            if issues[0] in {"provider_refusal", "offline"}:
                break
            repair = (
                "\n\nThe previous response failed validation: " + "; ".join(issues)
                + ". Generate one complete JSON assessment from the original request. "
                "Keep it concise enough to finish; include 3-5 concrete validation steps. "
                "Do not reproduce the invalid response or invent a verdict about the failure."
            )
        if issues:
            return {
                "status": "error", "agent": self.name, "mode": "idea_validation",
                "artifact_type": "seed_validation", "prompt": prompt_text,
                "error": "Idea Shaper could not produce a complete, valid assessment. Your idea has not been assessed; try again.",
                "summary": "Assessment failed; no verdict was generated.",
                "quality": {"status": "failed", "issues": issues, "attempts": len(diagnostics)},
                "diagnostics": diagnostics,
                "quality_flags": ["assessment_failed"],
            }
        steps = parsed.get("validation_steps", [])
        verdict = parsed.get("verdict", "")
        idea_summary = parsed.get("idea_summary", prompt_text[:80])
        return {
            "status": "ok",
            "agent": self.name,
            "mode": "idea_validation",
            "artifact_type": "seed_validation",
            "prompt": prompt_text,
            "idea_summary": idea_summary,
            "hypothesis": parsed.get("hypothesis", ""),
            "market_signal": parsed.get("market_signal", ""),
            "addressable_demand": parsed.get("addressable_demand", ""),
            "validation_steps": steps,
            "first_3_actions": parsed.get("first_3_actions", []),
            "risks": parsed.get("risks", []),
            "seven_day_sprint": parsed.get("seven_day_sprint", ""),
            "kill_criteria": parsed.get("kill_criteria", ""),
            "moat": parsed.get("moat", ""),
            "verdict": verdict,
            "verdict_rationale": parsed.get("verdict_rationale", ""),
            "confidence": None,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "summary": (
                f"Idea assessment: '{idea_summary}' — "
                f"Verdict: {verdict if verdict else 'See analysis'} | "
                f"{len(steps)} validation steps generated."
            ),
            "quality_flags": [
                "llm_synthesized",
                "structured_validation_framework",
                "prompt_responsive",
            ],
            "quality": {"status": "ok", "attempts": len(diagnostics), "factual_accuracy_verified": False},
            "diagnostics": diagnostics,
        }

    @staticmethod
    def _validation_errors(parsed: Dict[str, Any]) -> list[str]:
        if not parsed:
            return ["invalid_json"]
        issues = []
        for key in ("idea_summary", "hypothesis", "verdict", "verdict_rationale"):
            if not isinstance(parsed.get(key), str) or not parsed[key].strip():
                issues.append(f"{key} must be nonempty text")
        for key in ("market_signal", "addressable_demand", "seven_day_sprint", "kill_criteria", "moat"):
            if key in parsed and not isinstance(parsed[key], str):
                issues.append(f"{key} must be text")
        steps = parsed.get("validation_steps")
        if not isinstance(steps, list) or not 3 <= len(steps) <= 5:
            issues.append("validation_steps must contain 3-5 steps")
        else:
            for step in steps:
                if not isinstance(step, dict) or any(
                    not isinstance(step.get(key), str) or not step[key].strip()
                    for key in ("action", "method", "cost", "timeline", "success_indicator")
                ):
                    issues.append("each validation step needs action, method, cost, timeline and success_indicator")
                    break
        actions = parsed.get("first_3_actions")
        if not isinstance(actions, list) or len(actions) != 3 or any(not isinstance(item, str) or not item.strip() for item in actions):
            issues.append("first_3_actions must contain three text actions")
        risks = parsed.get("risks")
        if not isinstance(risks, list) or any(
            not isinstance(risk, dict) or any(not isinstance(risk.get(key), str) or not risk[key].strip() for key in ("risk", "severity", "mitigation"))
            for risk in risks
        ):
            issues.append("risks must be structured risk/severity/mitigation entries")
        return issues

    @staticmethod
    def _parse_input(prompt: Any):
        if isinstance(prompt, dict):
            text = str(
                prompt.get("prompt")
                or prompt.get("idea")
                or prompt.get("topic")
                or prompt.get("task")
                or prompt.get("content")
                or ""
            ).strip()
            ctx = prompt.get("context") or {}
        else:
            text = str(prompt or "").strip()
            ctx = {}
        return text, ctx

    @staticmethod
    def _extract_json(raw: str) -> Dict[str, Any]:
        text = str(raw or "").strip()
        # Strip markdown code fences (deepseek wraps JSON in ```json...```)
        import re as _re
        text = _re.sub(r"```(?:json)?\s*", "", text).strip()
        start = text.find("{")
        end = text.rfind("}")
        if start != -1 and end != -1 and end > start:
            try:
                parsed = json.loads(text[start : end + 1])
                return parsed if isinstance(parsed, dict) else {}
            except json.JSONDecodeError:
                pass
        return {}

    @staticmethod
    def _error_response(message: str) -> Dict[str, Any]:
        return {
            "status": "error",
            "agent": "PlantTheSeedAgent",
            "mode": "idea_validation",
            "artifact_type": "seed_validation",
            "error": message,
            "summary": f"PlantTheSeedAgent could not complete: {message}",
            "validation_steps": [],
            "confidence": 0.0,
            "quality": {"status": "failed", "issues": ["assessment_failed"]},
            "quality_flags": ["error"],
        }

    @staticmethod
    def _run_async(coro):
        """Safe sync->async bridge. Handles both running and fresh event loops."""
        try:
            asyncio.get_running_loop()
        except RuntimeError:
            return asyncio.run(coro)
        else:
            with concurrent.futures.ThreadPoolExecutor(max_workers=1) as pool:
                return pool.submit(asyncio.run, coro).result()
