# mammoth_os/agents/plant_the_seed_agent.py
"""
PlantTheSeedAgent — Elite Idea Validation Engine

Takes raw business ideas and delivers a structured validation framework:
testable hypothesis, market signals, 3 executable first actions, a 7-day
sprint plan, risks with mitigations, and a clear go/no-go verdict.

Zero templates. Every response generated by LLM against the actual prompt.
"""

from __future__ import annotations

import asyncio
import concurrent.futures
import json
import logging
from datetime import datetime, timezone
from typing import Any, Dict, Union

from .base_agent import BaseAgent

logger = logging.getLogger("mammoth.agents.plant_seed")


SYSTEM_PROMPT = """You are an elite business idea validation strategist working with True XXII Supply —
a small business operator in Boise, Idaho specializing in native plants, outdoor gear, and homesteading supplies.

Your job: take a raw seed idea and answer ONE question with precision:
"Is this worth pursuing — and exactly what do you do in the next 7 days to find out?"

Think like a YC partner crossed with a seasoned small business operator.
Be ruthlessly specific. No generic advice. Every action must be executable with <$100 and no team.

Respond in this exact JSON structure:
{
  "idea_summary": "One crisp sentence restating the core idea — sharpen it if the original is fuzzy",
  "hypothesis": "Testable statement: IF [True XXII Supply does X] THEN [we expect Y outcome] BECAUSE [underlying assumption Z]",
  "market_signal": "What trend, gap, or consumer behavior RIGHT NOW gives this idea legs — be specific about the Boise/Idaho market where relevant",
  "addressable_demand": "Who specifically wants this, how many of them exist in the target area, and how do you know",
  "validation_steps": [
    {
      "step": 1,
      "action": "Specific action to validate the core hypothesis",
      "method": "Exact method — e.g. '3 customer interviews with homesteaders in Boise FB groups', '$50 Meta ad to landing page', etc.",
      "cost": "$ estimate",
      "timeline": "Day 1-2 / This week / etc.",
      "success_indicator": "Specific observable YES — e.g. '2 of 3 people ask where to buy it'"
    },
    {
      "step": 2,
      "action": "...",
      "method": "...",
      "cost": "...",
      "timeline": "...",
      "success_indicator": "..."
    },
    {
      "step": 3,
      "action": "...",
      "method": "...",
      "cost": "...",
      "timeline": "...",
      "success_indicator": "..."
    }
  ],
  "first_3_actions": [
    "Action 1 — executable TODAY, zero cost, under 2 hours",
    "Action 2 — executable this week, under $25",
    "Action 3 — executable this week, validates real demand (not just interest)"
  ],
  "risks": [
    {
      "risk": "Specific risk that could kill this idea",
      "severity": "Low / Medium / High",
      "mitigation": "Concrete step to reduce this risk before committing resources"
    },
    {
      "risk": "...",
      "severity": "...",
      "mitigation": "..."
    }
  ],
  "seven_day_sprint": "What a focused, realistic 7-day validation sprint looks like — day by day or phase by phase",
  "kill_criteria": "The specific observable signal that tells you to stop and move on — be ruthless",
  "moat": "What would make this hard to copy once it works — even a small one",
  "verdict": "Plant it 🌱 / Prototype first 🔨 / Needs more research 🔍 / Kill it ❌",
  "verdict_rationale": "2-3 sentences — why this verdict, what's the biggest risk, what's the biggest opportunity"
}

Return ONLY the JSON. No preamble. No explanation outside the JSON.
"""


class PlantTheSeedAgent(BaseAgent):
    """Elite idea validation and business seed analysis agent."""

    name = "PlantTheSeedAgent"

    def run(self, prompt: Union[str, Dict[str, Any]]) -> Dict[str, Any]:
        prompt_text, context = self._parse_input(prompt)
        if not prompt_text:
            return self._error_response("No seed idea provided — describe the idea you want to validate.")
        try:
            return self._run_async(self._validate_idea(prompt_text, context))
        except Exception as exc:
            logger.error(f"PlantTheSeedAgent run failed: {exc}")
            return self._error_response(str(exc))

    def execute_action(
        self, action_type: str, target: str, details: Dict[str, Any]
    ) -> Dict[str, Any]:
        payload = dict(details or {})
        if "prompt" not in payload:
            payload["prompt"] = str(target or "").strip()
        return {**self.run(payload), "action": action_type, "target": target}

    async def _validate_idea(
        self, prompt_text: str, context: Dict[str, Any]
    ) -> Dict[str, Any]:
        from mammoth_os.llm_client import get_llm_client
        client = get_llm_client()
        context_block = ""
        if context:
            context_block = f"\n\nAdditional context:\n{json.dumps(context, indent=2)}"
        user_message = f"Seed idea to validate: {prompt_text}{context_block}"
        raw = await client.generate(
            f"{SYSTEM_PROMPT}\n\n{user_message}",
            max_tokens=2500,
            temperature=0.4,
            response_format={"type": "json_object"},
        )
        parsed = self._extract_json(raw)
        steps = parsed.get("validation_steps", [])
        verdict = parsed.get("verdict", "")
        confidence = round(
            min(0.93, 0.60
                + len(steps) * 0.05
                + (0.05 if parsed.get("hypothesis") else 0)
                + (0.05 if parsed.get("kill_criteria") else 0)
                + (0.05 if verdict else 0)),
            2,
        )
        idea_summary = parsed.get("idea_summary", prompt_text[:80])
        return {
            "status": "ok",
            "agent": self.name,
            "mode": "idea_validation",
            "artifact_type": "seed_validation",
            "prompt": prompt_text,
            "idea_summary": idea_summary,
            "hypothesis": parsed.get("hypothesis", ""),
            "market_signal": parsed.get("market_signal", ""),
            "addressable_demand": parsed.get("addressable_demand", ""),
            "validation_steps": steps,
            "first_3_actions": parsed.get("first_3_actions", []),
            "risks": parsed.get("risks", []),
            "seven_day_sprint": parsed.get("seven_day_sprint", ""),
            "kill_criteria": parsed.get("kill_criteria", ""),
            "moat": parsed.get("moat", ""),
            "verdict": verdict,
            "verdict_rationale": parsed.get("verdict_rationale", ""),
            "confidence": confidence,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "summary": (
                f"Seed validated: '{idea_summary}' — "
                f"Verdict: {verdict if verdict else 'See analysis'} | "
                f"{len(steps)} validation steps generated."
            ),
            "quality_flags": [
                "llm_synthesized",
                "structured_validation_framework",
                "prompt_responsive",
            ],
        }

    @staticmethod
    def _parse_input(prompt: Any):
        if isinstance(prompt, dict):
            text = str(
                prompt.get("prompt")
                or prompt.get("idea")
                or prompt.get("task")
                or prompt.get("content")
                or ""
            ).strip()
            ctx = prompt.get("context") or {}
        else:
            text = str(prompt or "").strip()
            ctx = {}
        return text, ctx

    @staticmethod
    def _extract_json(raw: str) -> Dict[str, Any]:
        text = str(raw or "").strip()
        # Strip markdown code fences (deepseek wraps JSON in ```json...```)
        import re as _re
        text = _re.sub(r"```(?:json)?\s*", "", text).strip()
        start = text.find("{")
        end = text.rfind("}")
        if start != -1 and end != -1 and end > start:
            try:
                return json.loads(text[start : end + 1])
            except json.JSONDecodeError:
                pass
        return {
            "idea_summary": text[:300] if text else "Unable to parse LLM response.",
            "validation_steps": [],
            "risks": [],
            "verdict": "Needs more research 🔍",
            "verdict_rationale": "Unable to parse structured response — see raw output above.",
        }

    @staticmethod
    def _error_response(message: str) -> Dict[str, Any]:
        return {
            "status": "error",
            "agent": "PlantTheSeedAgent",
            "mode": "idea_validation",
            "artifact_type": "seed_validation",
            "summary": f"PlantTheSeedAgent could not complete: {message}",
            "validation_steps": [],
            "confidence": 0.0,
            "quality_flags": ["error"],
        }

    @staticmethod
    def _run_async(coro):
        """Safe sync->async bridge. Handles both running and fresh event loops."""
        try:
            asyncio.get_running_loop()
        except RuntimeError:
            return asyncio.run(coro)
        else:
            with concurrent.futures.ThreadPoolExecutor(max_workers=1) as pool:
                return pool.submit(asyncio.run, coro).result()
