export const SUBSYSTEMS = [
  // ── CORE SYSTEMS ────────────────────────────────────────────────
  {
    id: 'command-center',
    name: 'Command Center v3',
    group: 'core',
    category: 'Operations',
    status: 'active',
    owner: 'MammothOS',
    lastUpdated: '2026-08-02',
    description: 'Primary command interface for all MammothOS operations and agent routing.',
  },
  {
    id: 'content-engine',
    name: 'Content Engine + Product Spotlight',
    group: 'core',
    category: 'Content',
    status: 'active',
    owner: 'MammothOS',
    lastUpdated: '2026-08-02',
    description: 'Drives content generation, brand voice, and product spotlight pipelines.',
  },
  {
    id: 'inventory-orders',
    name: 'Inventory + Orders + Fulfillment',
    group: 'core',
    category: 'Commerce',
    status: 'active',
    owner: 'MammothOS',
    lastUpdated: '2026-08-02',
    description: 'End-to-end inventory tracking, order management, and fulfillment automation.',
  },
  {
    id: 'customer-support',
    name: 'Customer Support + CRM',
    group: 'core',
    category: 'Customer',
    status: 'active',
    owner: 'MammothOS',
    lastUpdated: '2026-08-02',
    description: 'Customer relationship management and AI-powered support workflows.',
  },
  {
    id: 'compliance-audit',
    name: 'Compliance + Audit',
    group: 'core',
    category: 'Compliance',
    status: 'active',
    owner: 'MammothOS',
    lastUpdated: '2026-08-02',
    description: 'Wednesday-themed compliance monitoring, audit trails, and regulatory checks.',
  },
  {
    id: 'finance-accounting',
    name: 'Finance + Accounting',
    group: 'core',
    category: 'Finance',
    status: 'active',
    owner: 'MammothOS',
    lastUpdated: '2026-08-02',
    description: 'Financial reporting, accounting automation, and budget intelligence.',
  },
  {
    id: 'legal-policy',
    name: 'Legal + Policy',
    group: 'core',
    category: 'Legal',
    status: 'active',
    owner: 'MammothOS',
    lastUpdated: '2026-08-02',
    description: 'Policy management, legal document generation, and contract oversight.',
  },
  {
    id: 'hr-team',
    name: 'HR + Team Management',
    group: 'core',
    category: 'People',
    status: 'active',
    owner: 'MammothOS',
    lastUpdated: '2026-08-02',
    description: 'Human resources workflows, team tracking, and onboarding automation.',
  },
  {
    id: 'infrastructure-devops',
    name: 'Infrastructure + DevOps',
    group: 'core',
    category: 'Infrastructure',
    status: 'active',
    owner: 'MammothOS',
    lastUpdated: '2026-08-02',
    description: 'System infrastructure management, CI/CD pipelines, and deployment ops.',
  },
  {
    id: 'security-threat',
    name: 'Security + Threat Detection',
    group: 'core',
    category: 'Security',
    status: 'active',
    owner: 'MammothOS',
    lastUpdated: '2026-08-02',
    description: 'Wednesday dark-mode security layer — threat detection and system hardening.',
  },
  {
    id: 'ai-training',
    name: 'AI Training + Model Management',
    group: 'core',
    category: 'AI',
    status: 'active',
    owner: 'MammothOS',
    lastUpdated: '2026-08-02',
    description: 'Model training pipelines, version management, and evaluation workflows.',
  },
  {
    id: 'research-innovation',
    name: 'Research + Innovation',
    group: 'core',
    category: 'Research',
    status: 'active',
    owner: 'MammothOS',
    lastUpdated: '2026-08-02',
    description: 'Experimental research pipelines, innovation tracking, and discovery logging.',
  },
  {
    id: 'multi-agent-orchestration',
    name: 'Multi-Agent Orchestration',
    group: 'core',
    category: 'Agents',
    status: 'active',
    owner: 'MammothOS',
    lastUpdated: '2026-08-02',
    description: 'Coordinates all agents across subsystems — routing, scheduling, delegation.',
  },
  {
    id: 'world-simulation',
    name: 'World Simulation + Scenario Engine',
    group: 'core',
    category: 'Simulation',
    status: 'active',
    owner: 'MammothOS',
    lastUpdated: '2026-08-02',
    description: 'Scenario modelling, predictive world simulation, and outcome planning.',
  },
  {
    id: 'meta-cognition',
    name: 'Meta-Cognition + Self-Optimization',
    group: 'core',
    category: 'Meta',
    status: 'active',
    owner: 'MammothOS',
    lastUpdated: '2026-08-02',
    description: 'System self-analysis, performance tuning, and recursive improvement loops.',
  },
  {
    id: 'cosmic-layer',
    name: 'Cosmic Layer — Unified Meta-Architecture',
    group: 'core',
    category: 'Cosmic',
    status: 'active',
    owner: 'MammothOS',
    lastUpdated: '2026-08-02',
    description: 'The unified architectural layer binding all 21 subsystems into one field.',
  },
  {
    id: 'origin-layer',
    name: 'Origin Layer — Root Metaphysics',
    group: 'core',
    category: 'Cosmic',
    status: 'active',
    owner: 'MammothOS',
    lastUpdated: '2026-08-02',
    description: 'The foundational root layer — first principles and system axioms.',
  },
  {
    id: 'ascension-layer',
    name: 'Ascension Layer — Completion Subsystem',
    group: 'core',
    category: 'Cosmic',
    status: 'active',
    owner: 'MammothOS',
    lastUpdated: '2026-08-02',
    description: 'Final completion layer — system-wide convergence and mission fulfilment.',
  },

  // ── ATLAS + MammothOS CORE ───────────────────────────────────────
  {
    id: 'atlas-learning',
    name: 'ATLAS Learning Engine',
    group: 'atlas',
    category: 'Learning',
    status: 'active',
    owner: 'ATLAS',
    lastUpdated: '2026-08-02',
    description: 'Adaptive learning engine — lessons, exercises, XP, streaks, and tutor AI.',
  },
  {
    id: 'mammothos-cognitive',
    name: 'MammothOS Cognitive OS',
    group: 'atlas',
    category: 'OS',
    status: 'active',
    owner: 'ATLAS',
    lastUpdated: '2026-08-02',
    description: 'The cognitive operating system powering all MammothOS agent intelligence.',
  },
  {
    id: 'unified-field',
    name: 'Unified Field Activation',
    group: 'atlas',
    category: 'Cosmic',
    status: 'active',
    owner: 'ATLAS',
    lastUpdated: '2026-08-02',
    description: 'Activation of the unified field across all 21 subsystems — full coherence.',
  },
]

export const GROUP_LABELS = {
  core: 'Core Systems',
  atlas: 'ATLAS + MammothOS Core',
}

export const STATUS_COLORS = {
  active: '#4ade80',
  planned: '#facc15',
  complete: '#60a5fa',
}

export const CATEGORY_COLORS = {
  Operations:     '#4f8cff',
  Content:        '#a78bfa',
  Commerce:       '#34d399',
  Customer:       '#fb923c',
  Compliance:     '#f87171',
  Finance:        '#4ade80',
  Legal:          '#fbbf24',
  People:         '#e879f9',
  Infrastructure: '#38bdf8',
  Security:       '#f43f5e',
  AI:             '#c084fc',
  Research:       '#67e8f9',
  Agents:         '#a3e635',
  Simulation:     '#fb7185',
  Meta:           '#818cf8',
  Cosmic:         '#e2c4ff',
  Learning:       '#5eead4',
  OS:             '#93c5fd',
}
